[tools]
# https://github.com/oven-sh/bun/releases
bun = "1.3.9"
# https://github.com/golangci/golangci-lint/releases
golangci-lint = "2.10.1"
# https://github.com/go-courier/husky/releases
"github:go-courier/husky" = "1.8.1"
