---
modulekind: commonjs
targets:
  demo:
    services:
      /service/foo: Foo
      /service/demo: Demo
    package: github.com/foomo/gotsrpc/demo
    out: demo/output-commonjs/client.ts
    gorpc:
      - Foo
      - Demo
    tsrpc:
      - Foo
      - Demo

mappings:
  github.com/foomo/gotsrpc/demo:
    out: demo/output-commonjs/demo.ts
  github.com/foomo/gotsrpc/demo/nested:
    out: demo/output-commonjs/demo-nested.ts
...